---
apiVersion: v1
kind: Namespace
metadata:
  name: opto-portainer-demo
---
apiVersion: v1
kind: Secret
metadata:
  name: collector-secret
  namespace: opto-portainer-demo
type: Opaque
stringData:
  OPTO_HOST: "REPLACE_WITH_OPTO_HOSTNAME_OR_IP"
  OPTO_API_KEY: "REPLACE_WITH_OPTO_API_KEY"
